### ISSUE TITLE
Can not open the dowloaded data file

### ISSUE THREAD

**Issue by Xandra298** [lucazanella/lavad#10]
Thanks for the awsome work! 
I come across a problem when downloading the data file from the provided google drive link in readme.md. The zip files downloaded seems to be broken and can not be opened or unzipped. I have tried in both the windows and linux environment. I'd like to ask if the files are not complete or I need to use some specific tools. I wonder if anyone also have the same problem? 
Thank you so much!

(Data description: including captions, temporal summaries, indexes with their textual embeddings, and scores for the UCF-Crime and XD-Violence datasets.)

**Comment by lucazanella** [comment]
Hi,
Thank you for bringing this to my attention! I have re-created and re-uploaded the zip files. Please let me know if you can now download and extract them correctly.

**Comment by Xandra298** [comment]
> Hi, Thank you for bringing this to my attention! I have re-created and re-uploaded the zip files. Please let me know if you can now download and extract them correctly.

So glad to hear back and thanks for re-uploading the zip files. I have downloaded the files and still cannot extract them correctly.

**Comment by lucazanella** [comment]
Hi, I recently got to know that Windows users may have problems unzipping files I uploaded because some file names exceed the character limit allowed by Windows. Could you try using 7-Zip to extract the files, as suggested [here](https://superuser.com/questions/345894/how-to-unzip-zip-archives-that-have-more-than-260-symbols-in-their-name)?

**Comment by Xandra298** [comment]
> Hi, I recently got to know that Windows users may have problems unzipping files I uploaded because some file names exceed the character limit allowed by Windows. Could you try using 7-Zip to extract the files, as suggested [here](https://superuser.com/questions/345894/how-to-unzip-zip-archives-that-have-more-than-260-symbols-in-their-name)?

I use 7-zip on windows to extract the files as suggested, and it works! Thanks for your concern.
