### ISSUE TITLE
Step4: 04_query_llm.sh  AssertionError: no checkpoint files found in libs/llama/llama-2-13b-chat/

### ISSUE THREAD

**Issue by Puqi7** [lucazanella/lavad#16]
Thanks for your wonderful work and clear and clean open-source code. 

I met a question when running 04_query_llm.sh. Then I found that in the libs/llama/ there is no llama-2-13b-chat. May I know how you do this? 

Thanks!

**Comment by lucazanella** [comment]
Hi, thank you! I appreciate it.

To get started, please download `llama-2-13b-chat` from the official repository by following these [download instructions](https://github.com/meta-llama/llama#download). Once downloaded, place both the model and tokenizer files in the libs/llama directory.

Let me know if this helps!

**Comment by Puqi7** [comment]
Thanks a lot! I have solved this.

**Comment by Puqi7** [comment]
[](url)Hi，

I downloaded the llama-2-13b-chat, and put both files in the right position. 

I've met the following errors in 04_query_llm.sh. **It seems like there is a mismatch between the shape of the parameters defined in your model and those expected by the checkpoint being loaded.**  May I ask how you solved this? 

![Screenshot from 2024-11-11 12-35-28](https://github.com/user-attachments/assets/0f03e529-0425-47b1-beca-230c57a40726)
![Screenshot from 2024-11-11 12-35-48](https://github.com/user-attachments/assets/47064a79-23ab-4858-ab31-dd166fd6c8a9)

**Comment by lucazanella** [comment]
Hi! I noticed that you are using only one GPU, but you need two GPUs to run the llama-2-13b-chat model. If you have access to only one GPU, you should switch to the llama-2-7b-chat model. However, please note that you may need to tweak the prompt, as it may not work as well.
