### ISSUE TITLE
A problem about XD's captions.

### ISSUE THREAD

**Issue by KirinHao** [lucazanella/lavad#20]
Dear Luca,

Thank you very much for the work you have done, and I greatly appreciate the experimental data you have provided. I have a small question regarding the captions. In the data you provided, the captions/raw of **XD**'data only contains the inference results of blip2-flan-t5-xxl. I would like to fully reproduce your paper, so I need the captions inference results of the other four models. However, I do not have a powerful enough GPU to deploy the other models (for example, blip2-flan-t5-xl requires about 20G of memory and I try it successfully, but blip2-opt-6.7b-coco requires 30-40G of memory!). Could you share the raw captions obtained from the inference of the remaining models of XD? Thank you! 
![image](https://github.com/user-attachments/assets/676ed7a7-ffc2-42db-9f21-74b6a9fc8770)
![image](https://github.com/user-attachments/assets/0ab1861b-097b-4fc6-9f13-6f64ee10e399)

Wishing you a pleasant life!

**Comment by lucazanella** [comment]
Hi, thank you, I appreciate it! I have just uploaded the captions generated with the other four models to the same original link.

**Comment by KirinHao** [comment]
Thank you for your quick and helpful response! It’s been really useful.
