### ISSUE TITLE
Dataset development

### ISSUE THREAD

**Issue by Libyte** [lucazanella/lavad#4]
Thank you for your excellent work that has benefited me a lot, but I downloaded the original dataset annotation information and the annotation information given on google Driver during the reproduction process, and I would like to ask what should be done.

**Comment by lucazanella** [comment]
Hi, thank you!

I see you closed the issue, did you solve the problem? 

After downloading the videos, you'll need to convert them to frames. You can use [this script](https://github.com/lucazanella/lavad/blob/main/scripts/00_extract_frames.sh) as a reference. For each video, the annotation file (e.g., test.txt) should include the relative path of the video (without extension) to the `root_path` directory, the start frame index, end frame index, and label index. The label index is not used, so you can set it to a placeholder or remove this entry from [VideoRecord](https://github.com/lucazanella/lavad/blob/8f7c464269c69865edfde83eae265d06cc48c682/src/data/video_record.py#L5). 

Let me know if this helps!
