### ISSUE TITLE
how did you run caption?

### ISSUE THREAD

**Issue by Justhuayu** [lucazanella/lavad#5]
hello author，I ran 01_caption.sh on A6000 and found that it takes a long time (possibly several days) for XD_violence dataset to generate captions. How did you handle it? Is it useful for multi GPUs running?

**Comment by lucazanella** [comment]
Hi, unfortunately, I also experienced long processing times to get output from BLIP-2. To address this, I sped up the process by distributing the videos across multiple compute nodes, as I had access to a machine with many nodes. What `--batch_size` are you using?

**Comment by Justhuayu** [comment]
batch_size I used 1, now I split the data set into multiple folders and multi-process running

**Comment by lucazanella** [comment]
I also suggest increasing the batch size (using the `--batch-size` parameter) to maximize GPU utilization.

**Comment by Justhuayu** [comment]
Ok, I'll have a try. Thank you so much for taking the time to answer my questions.

**Comment by lucazanella** [comment]
Thanks to you for your interest in our work :)
