### ISSUE TITLE
Errors on my own dataset.

### ISSUE THREAD

**Issue by LBAMAD** [lucazanella/lavad#7]
Thank you for your open sourcing of this great work! When I tried to use this method on my own dataset, the following error occurred.

> File "/workspace/lavad/src/models/llm_anomaly_scorer.py", line 297, in <module>
>     run(
>   File "/workspace/lavad/src/models/llm_anomaly_scorer.py", line 248, in run
>     llm_anomaly_scorer.process_video(video, score_summary)
>   File "/workspace/lavad/src/models/llm_anomaly_scorer.py", line 177, in process_video
>     video_scores = self._score_temporal_summaries(video, temporal_summaries)
>   File "/workspace/lavad/src/models/llm_anomaly_scorer.py", line 151, in _score_temporal_summaries
>     video_scores = self._interpolate_unmatched_scores(video_scores)
>   File "/workspace/lavad/src/models/llm_anomaly_scorer.py", line 120, in _interpolate_unmatched_scores
>     video_scores = np.interp(list(scores.keys()), *zip(*valid_scores))
> TypeError: interp() missing 2 required positional arguments: 'xp' and 'fp'

I checked the value of **valid_scores** and found it to be empty, which means all **score** values are -1. How can I solve this problem? Looking forward to your reply. Thank you!

**Comment by lucazanella** [comment]
Hi and thank you for your interest in our work!

If all values are -1, it means that the [_parse_score](https://github.com/lucazanella/lavad/blob/1ad46c666d1b3cfb262f3dd84769acf873285056/src/models/llm_anomaly_scorer.py#L110) method could not match the LLM's response. I recommend checking the output of the LLM. If you are using a different LLM than `llama-2-13b-chat`, you might need to adjust the [format prompt](https://github.com/lucazanella/lavad/blob/1ad46c666d1b3cfb262f3dd84769acf873285056/slurm/ucf_crime/04_query_llm.sh#L23) or modify the [search pattern](https://github.com/lucazanella/lavad/blob/1ad46c666d1b3cfb262f3dd84769acf873285056/src/models/llm_anomaly_scorer.py#L111) used to parse the LLM's output.

Let me know if this helps!

**Comment by LBAMAD** [comment]
Thank you for your reply!
I adjust the LLM version to llama-2-13b-chat,and the problem has been resolved！
